In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)

DATA_DIR = Path("../data/raw")

households = pd.read_stata(DATA_DIR / "households_microdata.dta")
consagg = pd.read_stata(DATA_DIR / "consagg_microdata.dta")
food = pd.read_stata(DATA_DIR / "food_items_microdata.dta")
nonfood = pd.read_stata(DATA_DIR / "nonfood_items_microdata.dta")

print("Households:", households.shape)
print("Consumption:", consagg.shape)
print("Food:", food.shape)
print("Non-food:", nonfood.shape)

Households: (17042, 33)
Consumption: (16963, 22)
Food: (373717, 24)
Non-food: (349464, 15)

## Data Understanding

In [13]:
for name, df in {
    "households": households,
    "consagg": consagg,
    "food": food,
    "nonfood": nonfood
}.items():

    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

============================================================
HOUSEHOLDS
============================================================
Shape: (17042, 33)

Columns:
['clid', 'strid', 'hhid', 'county', 'resid', 'strat', 'a11_1', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10', 'e11', 'e12', 'f_b01', 'f_b02', 'f_b03', 'f_b04', 'f_b05', 'f_b06', 'f_b07', 'f_b08', 'qrt', 'hhsize', 'adq_scale', 'weight_hh', 'weight_pop', 'weight_adq']

============================================================
CONSAGG
============================================================
Shape: (16963, 22)

Columns:
['clid', 'hhid', 'resid', 'strat', 'county', 'weight_hh', 'weight_pop', 'weight_adq', 'hhsize', 'qrt', 'pdeflator', 'padqfdcons', 'padqnfdcons', 'padqexp', 'padqrent', 'padqeduc', 'pl_food', 'pl_abs', 'food_poor', 'abs_poor', 'hc_poor', 'adq_scale']

============================================================
FOOD
============================================================
Shape: (373717, 24)

Columns:
['clid', 'strid', 'hhid', 'fooditem_code', 'f5_amnt', 'f5_qtyb', 'f6_qty', 'f7_qty', 'f8_qty', 'f9_qty', 'qcons', 'uv', 'hhsize', 'adq_scale', 'strat', 'resid', 'county', 'province', 'qrt', 'weight_hh', 'weight_pop', 'weight_adq', 'calories', 'coicop']

============================================================
NONFOOD
============================================================
Shape: (349464, 15)

Columns:
['clid', 'strid', 'hhid', 'nonfooditem_code', 'strat', 'nfcons', 'weight_hh', 'weight_pop', 'weight_adq', 'coicopcode', 'county', 'resid', 'hhsize', 'adq_scale', 'qrt']

In [14]:
households.head()

,clid,strid,hhid,county,resid,strat,a11_1,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,f_b01,f_b02,f_b03,f_b04,f_b05,f_b06,f_b07,f_b08,qrt,hhsize,adq_scale,weight_hh,weight_pop,weight_adq
0,1.0,1.0,1.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Concrete/ Cement/Terrazo,Iron sheets/Decra/Versatile,Stone with lime/cement,Public tap/Standpipe,Flush to Septic tank,Electricity,LPG (gas),No,Yes,Yes,Yes,Yes,Yes,Yes,No,1,1.0,1.0,1476.448412,1234.732666,1234.732666
1,1.0,2.0,2.0,Mombasa,Urban,1,Non-farming,1,1,1,SWAHILI,PAYS RENT/LEASE,Wall to wall Carpet,Iron sheets/Decra/Versatile,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,Paraffin,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,1,1.0,1.0,1476.448412,1234.732666,1234.732666
2,1.0,3.0,3.0,Mombasa,Urban,1,Non-farming,1,1,1,SWAHILI,PAYS RENT/LEASE,Wall to wall Carpet,Iron sheets/Decra/Versatile,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,1,2.0,2.0,1476.448412,2469.465332,2469.465332
3,1.0,4.0,4.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Concrete/ Cement/Terrazo,Concrete/Cement,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),No,No,No,No,No,No,No,No,1,2.0,2.0,1476.448412,2469.465332,2469.465332
4,1.0,5.0,5.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Ceramic tiles,Concrete/Cement,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,1,2.0,2.0,1476.448412,2469.465332,2469.465332

In [15]:
households.info()

<class 'pandas.DataFrame'>
RangeIndex: 17042 entries, 0 to 17041
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   clid        17042 non-null  float32
 1   strid       17042 non-null  float32
 2   hhid        17042 non-null  float32
 3   county      17042 non-null  category
 4   resid       17042 non-null  category
 5   strat       17042 non-null  int8
 6   a11_1       17039 non-null  category
 7   e1          17042 non-null  int8
 8   e2          17042 non-null  int8
 9   e3          17042 non-null  int8
 10  e4          17042 non-null  category
 11  e5          17042 non-null  category
 12  e6          17042 non-null  category
 13  e7          17042 non-null  category
 14  e8          17042 non-null  category
 15  e9          17040 non-null  category
 16  e10         17042 non-null  category
 17  e11         17042 non-null  category
 18  e12         17042 non-null  category
 19  f_b01       17038 non-null  category
 20  f_b02       17038 non-null  category
 21  f_b03       17038 non-null  category
 22  f_b04       17038 non-null  category
 23  f_b05       17038 non-null  category
 24  f_b06       17038 non-null  category
 25  f_b07       17038 non-null  category
 26  f_b08       17038 non-null  category
 27  qrt         17042 non-null  int8
 28  hhsize      17042 non-null  float32
 29  adq_scale   17042 non-null  float32
 30  weight_hh   17042 non-null  float64
 31  weight_pop  17042 non-null  float32
 32  weight_adq  17042 non-null  float32
dtypes: category(20), float32(7), float64(1), int8(5)
memory usage: 1022.4 KB

In [16]:
households.describe()

,clid,strid,hhid,strat,e1,e2,e3,qrt,hhsize,adq_scale,weight_hh,weight_pop,weight_adq
count,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000,17042.000000
mean,751.666626,8227.416016,8521.500000,48.835465,1.614893,3.020068,1.952060,2.515608,4.029867,3.254230,747.744429,2911.739502,2360.901367
std,417.534393,4733.559082,4919.746094,26.653108,0.917958,1.798211,1.044175,1.123612,2.366459,1.827842,688.325913,2859.542725,2283.192383
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.650000,56.689375,53.583584,53.583584
25%,400.000000,4161.250000,4261.250000,27.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,382.229886,1019.933655,867.374390
50%,769.000000,8215.500000,8521.500000,50.000000,1.000000,3.000000,2.000000,3.000000,4.000000,3.000000,617.539299,2147.826172,1744.623901
75%,1114.000000,12285.750000,12781.750000,72.000000,2.000000,4.000000,2.000000,4.000000,5.000000,4.300000,843.763283,3876.900635,3099.051514
max,1466.000000,16321.000000,17042.000000,92.000000,15.000000,18.000000,12.000000,4.000000,21.000000,15.160000,7784.728299,45699.000000,43033.226562

## Identifying the households

In [17]:
print("HOUSEHOLDS")
print(households.columns.tolist())

print("\nCONSAGG")
print(consagg.columns.tolist())

print("\nFOOD")
print(food.columns.tolist())

print("\nNONFOOD")
print(nonfood.columns.tolist())

HOUSEHOLDS
['clid', 'strid', 'hhid', 'county', 'resid', 'strat', 'a11_1', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10', 'e11', 'e12', 'f_b01', 'f_b02', 'f_b03', 'f_b04', 'f_b05', 'f_b06', 'f_b07', 'f_b08', 'qrt', 'hhsize', 'adq_scale', 'weight_hh', 'weight_pop', 'weight_adq']

CONSAGG
['clid', 'hhid', 'resid', 'strat', 'county', 'weight_hh', 'weight_pop', 'weight_adq', 'hhsize', 'qrt', 'pdeflator', 'padqfdcons', 'padqnfdcons', 'padqexp', 'padqrent', 'padqeduc', 'pl_food', 'pl_abs', 'food_poor', 'abs_poor', 'hc_poor', 'adq_scale']

FOOD
['clid', 'strid', 'hhid', 'fooditem_code', 'f5_amnt', 'f5_qtyb', 'f6_qty', 'f7_qty', 'f8_qty', 'f9_qty', 'qcons', 'uv', 'hhsize', 'adq_scale', 'strat', 'resid', 'county', 'province', 'qrt', 'weight_hh', 'weight_pop', 'weight_adq', 'calories', 'coicop']

NONFOOD
['clid', 'strid', 'hhid', 'nonfooditem_code', 'strat', 'nfcons', 'weight_hh', 'weight_pop', 'weight_adq', 'coicopcode', 'county', 'resid', 'hhsize', 'adq_scale', 'qrt']

In [18]:
datasets = {
    "households": set(households.columns),
    "consagg": set(consagg.columns),
    "food": set(food.columns),
    "nonfood": set(nonfood.columns)
}

common = (
    datasets["households"]
    & datasets["consagg"]
    & datasets["food"]
    & datasets["nonfood"]
)

print("Common columns:")
print(sorted(common))

Common columns:
['adq_scale', 'clid', 'county', 'hhid', 'hhsize', 'qrt', 'resid', 'strat', 'weight_adq', 'weight_hh', 'weight_pop']

## Data Cleaning

In [19]:
# ==============================
# DATA CLEANING
# ==============================

# 1. Check the data
print(df.shape)
print(df.head())
print(df.isnull().sum())

# 2. Remove duplicate records
df = df.drop_duplicates()

# 3. Remove completely empty columns
df = df.dropna(axis=1, how="all")

# 4. Clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# 5. Check missing values again
print(df.isnull().sum())

# 6. Check the cleaned dataset
print("Cleaned data shape:", df.shape)

(349464, 15)
    clid    strid     hhid           nonfooditem_code  strat        nfcons  \
0  922.0  10101.0  10450.0       MOBILE PHONE AIRTIME     60   8907.736328
1  922.0  10101.0  10450.0                   FIREWOOD     60  12000.000977
2  922.0  10101.0  10450.0            BARBER SERVICES     60    720.000000
3  922.0  10101.0  10450.0            PETROLEUM JELLY     60    480.000000
4  922.0  10101.0  10450.0  TOILET PAPER/TISSUE PAPER     60    480.000000

    weight_hh   weight_pop   weight_adq  \
0  340.203235  1686.530273  1194.063354
1  340.203235  1686.530273  1194.063354
2  340.203235  1686.530273  1194.063354
3  340.203235  1686.530273  1194.063354
4  340.203235  1686.530273  1194.063354

                                          coicopcode    county  resid  hhsize  \
0                      Information and communication  Laikipia      1       5
1   Housing, water, electricity, gas and other fuels  Laikipia      1       5
2  Personal care, social protection and miscellan...  Laikipia      1       5
3  Personal care, social protection and miscellan...  Laikipia      1       5
4  Personal care, social protection and miscellan...  Laikipia      1       5

   adq_scale  qrt
0       3.54    4
1       3.54    4
2       3.54    4
3       3.54    4
4       3.54    4
clid                 0
strid                0
hhid                 0
nonfooditem_code     0
strat                0
nfcons               0
weight_hh            0
weight_pop           0
weight_adq           0
coicopcode          11
county               0
resid                0
hhsize               0
adq_scale            0
qrt                  0
dtype: int64
clid                 0
strid                0
hhid                 0
nonfooditem_code     0
strat                0
nfcons               0
weight_hh            0
weight_pop           0
weight_adq           0
coicopcode          11
county               0
resid                0
hhsize               0
adq_scale            0
qrt                  0
dtype: int64
Cleaned data shape: (349464, 15)

### Remove missing records

In [20]:
df = df.dropna(subset=["coicopcode"])

In [24]:
print(df.shape)
print(df.isnull().sum().sum())

(349453, 15)
0

In [25]:
HOUSEHOLD_ID = "hhid"

In [26]:
print(df[HOUSEHOLD_ID].nunique())

16962

In [27]:
FOOD_VALUE = "PUT_FOOD_EXPENDITURE_VARIABLE_HERE"
NONFOOD_VALUE = "PUT_NONFOOD_EXPENDITURE_VARIABLE_HERE"

In [30]:
FOOD_VALUE = "f5_amnt"
NONFOOD_VALUE = "nfcons"

nonfood_agg = (
    nonfood.groupby(HOUSEHOLD_ID)[NONFOOD_VALUE]
    .sum()
    .reset_index(name="nonfood_consumption")
)

### Merge the datasets

In [31]:
df = households.copy()

### Merge Aggregate Consumption

In [32]:
df = df.merge(
    consagg,
    on=HOUSEHOLD_ID,
    how="left",
    validate="one_to_one"
)

In [34]:
food_agg = (
    food.groupby(HOUSEHOLD_ID, as_index=False)[FOOD_VALUE]
    .sum()
    .rename(columns={FOOD_VALUE: "food_consumption"})
)

df = df.merge(
    food_agg,
    on=HOUSEHOLD_ID,
    how="left",
    validate="one_to_one"
)

In [35]:
df = df.merge(
    nonfood_agg,
    on=HOUSEHOLD_ID,
    how="left",
    validate="one_to_one"
)

### Confirm Data Integration/Merge

In [36]:
print(df.shape)
df.head()

(17042, 56)

,clid_x,strid,hhid,county_x,resid_x,strat_x,a11_1,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,f_b01,f_b02,f_b03,f_b04,f_b05,f_b06,f_b07,f_b08,qrt_x,hhsize_x,adq_scale_x,weight_hh_x,weight_pop_x,weight_adq_x,clid_y,resid_y,strat_y,county_y,weight_hh_y,weight_pop_y,weight_adq_y,hhsize_y,qrt_y,pdeflator,padqfdcons,padqnfdcons,padqexp,padqrent,padqeduc,pl_food,pl_abs,food_poor,abs_poor,hc_poor,adq_scale_y,food_consumption,nonfood_consumption
0,1.0,1.0,1.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Concrete/ Cement/Terrazo,Iron sheets/Decra/Versatile,Stone with lime/cement,Public tap/Standpipe,Flush to Septic tank,Electricity,LPG (gas),No,Yes,Yes,Yes,Yes,Yes,Yes,No,1,1.0,1.0,1476.448412,1234.732666,1234.732666,1.0,Urban,1.0,Mombasa,1476.448412,1234.732666,1234.732666,1.0,1.0,1.342302,10140.381836,10599.569336,20739.951172,3724.945312,0.000000,2904.953613,7192.953613,0.0,0.0,0.0,1.0,3645.0,110733.820312
1,1.0,2.0,2.0,Mombasa,Urban,1,Non-farming,1,1,1,SWAHILI,PAYS RENT/LEASE,Wall to wall Carpet,Iron sheets/Decra/Versatile,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,Paraffin,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,1,1.0,1.0,1476.448412,1234.732666,1234.732666,1.0,Urban,1.0,Mombasa,1476.448412,1234.732666,1234.732666,1.0,1.0,1.027851,3960.771240,10853.593750,14814.364258,1751.226440,0.000000,2904.953613,7192.953613,0.0,0.0,0.0,1.0,1220.0,112270.531250
2,1.0,3.0,3.0,Mombasa,Urban,1,Non-farming,1,1,1,SWAHILI,PAYS RENT/LEASE,Wall to wall Carpet,Iron sheets/Decra/Versatile,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,1,2.0,2.0,1476.448412,2469.465332,2469.465332,1.0,Urban,1.0,Mombasa,1476.448412,2469.465332,2469.465332,2.0,1.0,1.079543,3995.138184,19204.060547,23199.199219,1945.267822,3751.588623,2904.953613,7192.953613,0.0,0.0,0.0,2.0,3260.0,349958.562500
3,1.0,4.0,4.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Concrete/ Cement/Terrazo,Concrete/Cement,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),No,No,No,No,No,No,No,No,1,2.0,2.0,1476.448412,2469.465332,2469.465332,1.0,Urban,1.0,Mombasa,1476.448412,2469.465332,2469.465332,2.0,1.0,1.052978,7063.871582,8010.042969,15073.915039,3086.485107,0.000000,2904.953613,7192.953613,0.0,0.0,0.0,2.0,4080.0,124425.523438
4,1.0,5.0,5.0,Mombasa,Urban,1,Non-farming,2,2,1,FLAT,PAYS RENT/LEASE,Ceramic tiles,Concrete/Cement,Stone with lime/cement,Water Vendor,Flush to Septic tank,Electricity,LPG (gas),Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,1,2.0,2.0,1476.448412,2469.465332,2469.465332,1.0,Urban,1.0,Mombasa,1476.448412,2469.465332,2469.465332,2.0,1.0,1.100230,3429.067139,8284.068359,11713.135742,4544.504395,0.000000,2904.953613,7192.953613,0.0,0.0,0.0,2.0,1800.0,98745.132812

## Feature Engineering